alias reload!='. ~/.zshrc'
alias -r single='sudo ~/singlize'
alias -r dual='sudo ~/dualize'
alias -r wmount='sudo mount /dev/sda3 /mnt/windows'
alias -r pmount='sudo mount /dev/sdc /mnt/usb'
alias -r vedit='vim ~/.vimrc'
alias -r zedit='vim ~/.zshrc.local'
alias -r upgrade='sudo eix-sync && sudo emerge -auND world'
